sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t naren9990/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true naren9990/react-test npm run test

after_success:
  - docker build -t naren9990/multi-client ./client
  - docker build -t naren9990/multi-nginx ./nginx
  - docker build -t naren9990/multi-server ./server
  - docker build -t naren9990/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push naren9990/multi-client
  - docker push naren9990/multi-nginx
  - docker push naren9990/multi-server
  - docker push naren9990/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-586850696382'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
